apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-10T16:37:40Z"
  name: carts-canary
  resourceVersion: "35237"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 757956f0-62ed-11ea-81f1-42010a8000a4
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
